version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: '09:30'
    timezone: Europe/Paris
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 99
  labels:
  - dependencies
