---
# Signature checks breaks many scripts, and mostly rebases. It is a pain !
verify_signatures: false

PostCheckout:
  BundleInstall:
    enabled: true

PostMerge:
  BundleInstall:
    enabled: true

PreCommit:
  ALL:
    # Treat all warnings as failures
    on_warn: fail

    # Get results faster on big commits
    parallelize: true

    # Only check filed changed in the commit
    require_files: true

  BrokenSymlinks:
    enabled: true

  # When we do partial commits, RuboCop could fail as only part of the
  # modified file is committed (and it might not be a valid Ruby file)
  # File should (almost) always be valid because our editor(s) run
  # RuboCop on file save. Rarely do we commit an invalid Ruby file.
  RuboCop:
    enabled: false

  TrailingWhitespace:
    enabled: true

  JsonLint:
    enabled: true

  BundleCheck:
    enabled: true

CommitMsg:
  CapitalizedSubject:
    enabled: false

  TextWidth:
    enabled: true
    max_subject_width: 72
