require:
  - standard/cop/semantic_blocks
  - rubocop-minitest
  - rubocop-performance

inherit_gem:
  relaxed-rubocop: .rubocop.yml
  standard: config/base.yml

AllCops:
  NewCops: "enable"
  TargetRubyVersion: 2.7
