require:
  - standard/cop/block_single_line_braces
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance

inherit_gem:
  relaxed-rubocop: .rubocop.yml
  standard: config/base.yml

AllCops:
  NewCops: "enable"
  TargetRubyVersion: 3.1
