version: 2
references:
  unit: &unit
    run:
      name: Run test suite
      command: bundle exec rake
  restore: &restore
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
  bundle: &bundle
    run:
      name: install dependencies
      command: gem install bundler && bundle install --path vendor/bundle
  save: &save
    save_cache:
      paths:
        - ./vendor/bundle
      key: v1-dependencies-{{ checksum "Gemfile.lock" }}
jobs:
  "ruby-2.5":
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - <<: *restore
      - <<: *bundle
      - <<: *save
      - <<: *unit
  "ruby-2.6":
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - <<: *restore
      - <<: *bundle
      - <<: *save
      - <<: *unit
  "jruby":
    docker:
      - image: circleci/jruby:latest
    steps:
      - checkout
      - <<: *restore
      - <<: *bundle
      - <<: *save
      - <<: *unit

workflows:
  version: 2
  build:
    jobs:
      - "ruby-2.6"
      #
      # Scalingo where this app runs needs a Ruby version in the Gemfile
      # so we have to skip testing on this version
      # - "ruby-2.5"
      #
      # Puma 4 not compatible yet
      # - "jruby"
